[tool.black]
line-length = 100
extend-exclude = '''
    .tox
    .venv
'''

[tool.isort]
profile = "black"
sources = ["src", "bin"]
line_length = 100

[tool.mypy]
plugins = ["pydantic.mypy"]
exclude = [
    ".tox",
    '.venv'
]
strict = true
show_error_codes = true
show_column_numbers = true

[tool.ruff]
# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default.
select = [
  "A",   # flake8-builtins
  "E",   # pycodestyle errors
  "W",   # pycodestyle warnings
  "F",   # pyflakes
  "C4",  # flake8-comprehensions
  "B",   # flake8-bugbear
  "N",   # pep8-naming
  "C90", # mccabe
  "S",   # flake8-bandit
  "T20", # flake8-print
  "ERA", # eradicate
  "RUF", # Ruff-specific rules
  "TRY", # tryceratops
  "D",   # pydocstyle
  # "I",  # isort
]
ignore = [
  "D1",   # pydocstyle: missing docstrings
  "D203", # pydocstyle: one-blank-line-before-class
  "D213", # pydocstyle: multi-line-summary-second-line
  "D300", # pydocstyle: single double quotes
  "N815", # pydocstyle: variable in mixed case
  "N802", # pydocstyle: function name in upper case
  "D205", # pydocstyle: no blank line between summary line and description
  "D400", # pydocstyle: first line of docstring without period
  "D415", # pydocstyle: first line of dockstring without period, question mark, or exclamation point
  "D401", # pydocstyle: first line of dockstring not in imperative mood
]
line-length = 100

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"] # imported but unused
